resolvers += Resolver.bintrayRepo("oyvindberg", "converter")

addSbtPlugin("ch.epfl.scala"               % "sbt-scalajs-bundler"      % "0.20.0")
addSbtPlugin("com.eed3si9n"                % "sbt-assembly"             % "0.15.0")
addSbtPlugin("com.typesafe.sbt"            % "sbt-native-packager"      % "1.7.6")
addSbtPlugin("io.spray"                    % "sbt-revolver"             % "0.9.1")
addSbtPlugin("org.portable-scala"          % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scala-js"                % "sbt-scalajs"              % "1.4.0")
addSbtPlugin("org.scalablytyped.converter" % "sbt-converter"            % "1.0.0-beta29.2")
addSbtPlugin("org.scalameta"               % "sbt-scalafmt"             % "2.4.2")
