addSbtPlugin("ch.epfl.scala"               % "sbt-scalajs-bundler"      % "0.20.0")
addSbtPlugin("com.eed3si9n"                % "sbt-assembly"             % "1.1.0")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager"      % "1.9.5")
addSbtPlugin("io.spray"                    % "sbt-revolver"             % "0.9.1")
addSbtPlugin("org.portable-scala"          % "sbt-scalajs-crossproject" % "1.1.0")
addSbtPlugin("org.scala-js"                % "sbt-scalajs"              % "1.7.1")
addSbtPlugin("org.scalablytyped.converter" % "sbt-converter"            % "1.0.0-beta32")
addSbtPlugin("org.scalameta"               % "sbt-scalafmt"             % "2.4.3")
