version: '3.8'

services:

  mongo:
    image: mongo:4.2.11
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongoclient:
    image: mongoclient/mongoclient:4.0.1
    ports:
      - 3000:3000
    volumes:
      - /tmp/mongoclient/db:/data/db